// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvQEZsaUDzCD3EWBVtYFzZ2w6dKtfYbyI',
    appId: '1:876486706780:web:cfd09b6ebd52c72fed4899',
    messagingSenderId: '876486706780',
    projectId: 'crafty-bay-2df40',
    authDomain: 'crafty-bay-2df40.firebaseapp.com',
    storageBucket: 'crafty-bay-2df40.firebasestorage.app',
    measurementId: 'G-C290064H91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrXhtbNB00-z-hW9cbcode2so5tZfaacA',
    appId: '1:876486706780:android:060a656cf1a06e86ed4899',
    messagingSenderId: '876486706780',
    projectId: 'crafty-bay-2df40',
    storageBucket: 'crafty-bay-2df40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC02NAwLWOjMNznEW_Tql89U3nmaqxcSyg',
    appId: '1:876486706780:ios:94d3fc0aee5d8afbed4899',
    messagingSenderId: '876486706780',
    projectId: 'crafty-bay-2df40',
    storageBucket: 'crafty-bay-2df40.firebasestorage.app',
    iosBundleId: 'com.alamin.craftyBay',
  );
}
